version: '3.4'

networks:
  postgres:
    driver: bridge

services:
  frontendservice:
    image: ${DOCKER_REGISTRY-}frontendservice
    env_file:
      - dev.env
    environment:
      PostgreSQL: ${PostgreSQL}
    networks:
      - postgres
    links:
      - postgres  
    build:
      context: .
      dockerfile: FrontendService/Dockerfile
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - dev.env
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "postgres"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped