
name: build-frontend-server

on:
  push:

  pull_request:
    
jobs:
  build-frontend-server:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 16.x ]  
 
    steps:
    
    - name: Git clone our repo
      uses: actions/checkout@v2
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install all dependencies 
      run: |
        cd ./Frontend
        pwd
        yarn install 
        
    - name: Build frontend server
      run: yarn build
        
